### ISSUE TITLE
生成nav嵌套导航的时候报错

### ISSUE THREAD

**Issue by Jioho** [boboidream/vuepress-plugin-rpurl#1]
在 `replaceNav` 方法中 

重新调用 replaceNav 的时候，少传了一个 options 导致调用  replaceAll 的时候报错：`TypeError: Cannot read property 'map' of undefined`

```js
if (nav.items) {
   replaceNav(nav.items) // 这边应该加一个参数 options
}
```

**Comment by boboidream** [comment]
感谢，已合并 fix
